docs/partners/integration_guide.md
docs/partners/introduction.md

Tried to make things a bit more concise. @fameal @lehnberg

Edit partner program copy

---

docs/developers/v2/DEPLOYMENT.md

Change Log:
* Refactor docs to point to correct links
* Update deployment steps to include Health check setup
* Add health check section to docs

feat: add health check docs

---

docs/security/index.md
docs/securityResearchers/index.md
docusaurus.config.js

This PR:
- renames Security section to Security
- adds a first attempt of general info around yearn's security

feat: add Security section

---

versioned_docs/version-0.4.2/yearn-api.md
versioned_sidebars/version-0.4.2-sidebars.json

This was created while we were migrating docs.

feat: yearn-api

---

docusaurus.config.js

refactor: revert baseUrl change

---

docs/partners/submit_pr.md
sidebars/sidebarsPartners.js

Add docs on how to submit a PR for partners.

feat: add how to submit PR to partners

---

docs/contributing/contribute.md

update links intro for contributors

fix: update links contributions

---

docusaurus.config.js
src/components/HomepageFeatures.js
src/components/HomepageFeatures.module.css
src/pages/index.js
src/pages/index.module.css

Figma Design Layout: https://www.figma.com/file/wTtVeBzSkNIw4T6Fl355gx/Learn-Yearn?node-id=0%3A1
- Updated layout to "Learn" and "Build"
- Styled cards and hover colors
- Added footer sections and additional links

Updated UI to Ivan Kokorev's new design

---

docs/getting-started/products/yvaults/vault-tokens.md
src/css/custom.css
versioned_docs/version-0.4.3/yearn-sdk/yearn-stack.md

Fix for #50 
updated style for images for darkmode compatibility
added ipfs metadata image

Issue 50 fix

---

docusaurus.config.js

fix: change baseUrl and url

---

docs/resources/links.md

feat: add token terminal analytics to links

---

docs/developers/v2/additional-resources.md
docs/getting-started/products/yvaults/vaults-and-strategies.md
docs/resources/faq.md
docs/resources/links.md
versioned_docs/version-0.4.2/getting-started.md

Tested the changes on local server.

fix: update yearn vault state link, closes #112

---

docusaurus.config.js

feat: add new dev survey, closes #113

---

docs/developers/v2/EMERGENCY.md
docs/resources/defi-glossary.md
versioned_docs/version-0.4.3/smart-contracts/test/TestGuestList.md

close #121 
easier to merge after #129 is merged, I can rebase to main if it's a better practice!

refactor: change glossary link

---

docs/getting-started/guides/how-to-understand-yvault-roi.md

Dark-mode compatible image
Old https://i.imgur.com/g2I40pQ.png
New https://i.imgur.com/CJnIJub.png

fix: roi projections image

---

docs/contributing/documentation/writing-style-guide.md

close #133 
Also removes a unused section header

refactor: add audit citation guidelines

---

mlc_config.json

refactor: ignore etherscan links on linter

---

docs/contributing/documentation/writing-style-guide.md
docs/contributing/governance/governance-and-operations.md
docs/contributing/governance/proposal-process.md
docs/getting-started/products/iron-bank/faq.md
docs/getting-started/products/yvaults/overview.md

close #144 
I scanned all MD files manually but a smarter person would use regex 🤣

refactor: remove relative links

---

docs/developers/v2/CONTRACTS_REVIEW.md

This document is a guideline to develop/review smart contracts, especially new strategies.
It is based on our experience and the best practices used by other protocols.
We will be adding (in new PRs) checklist for our different flavors of strategies.

Add Smart Contracts Review Guideline

---

docs/getting-started/guides/how-to-understand-yvault-roi.md

closes #149
updates ROI section with information on where to find it in v3 interface and also accommodates APY usage

update roi guide for v3 interface

---

docs/getting-started/intro.md
docs/resources/faq.md
docs/security/index.md
docs/security/multisig.md
sidebars/sidebarsSecurity.js

First pass on multisig documentation. The missing attestations will be added once they're posted publicly

Add multisig documentation

---

docs/resources/faq.md

refactor: remove earn faq link

---

docs/partners/introduction.md

As discussed with Corn the old model was incorrect, this PR should fix the model!

fix: partnership profit-sharing model

---

docs/getting-started/using-yearn.md

closes #173
adds arbitrum on text and change image to this one:

chore: add arbitrum

---

docs/contributing/governance/governance-and-operations.md

fix typo at multisig section

---

docs/partners/introduction.md

update partnership program description

---

docs/developers/v2/DEPLOYMENT.md
docs/developers/v2/yswaps.md
sidebars/sidebarsDevelopers.js

close #192 
you can preview the document at https://hackmd.io/CA00W0F1QviUVzuWbgf_jw
or run this branch locally and navigate to http://localhost:3000/developers/v2/yswaps (it's prettier here!)

add yswaps documentation

---

docs/getting-started/guides/how-to-understand-yvault-roi.md

fixes https://github.com/yearn/yearn-devdocs/issues/205

fix broken link

---

docs/getting-started/guides/how-apy-works.md
docs/getting-started/guides/how-to-understand-yvault-roi.md
docs/getting-started/guides/how-to-understand-yveCRV.md
sidebars/sidebarsGettingStarted.js

add APYs guide

---

docs/security/risk-score.md

signalizes better what is at draft stage and what is already used

add risk scores proposal labels

---

docs/developers/v2/yswaps.md

improve linebreaks that weren't applied properly
preview at: https://yearn-docs-git-fork-marcoworms-improve-yswaps.yearn.farm/developers/v2/yswaps
*all broken markdown-linter links are intended since it's a private repo

improve yswaps linebreaks

---

docs/contributing/operations/budget.md
sidebars/sidebarsContributing.js

closes #216
Preview at: https://yearn-docs-git-fork-marcoworms-add-budget.yearn.farm/contributing/operations/budget
This was all info I found in the telegram groups about the budget process, let me know if there is anything else to add!

Add budget process

---

README.md

fix readme link to website, also improves markdown heading usage

fix readme link to website

---

docs/developers/v2/getting-started.md

apply reviews requested and closes  #168

hijack PR #168 to apply review and close it (update getting started by storm)

---

docs/developers/v2/fork-yearn-ui.md
sidebars/sidebarsDevelopers.js

Complements [Macarena Finance](https://github.com/yearn/macarena-finance) readme with a more detailed guide on how to fork and change yearn UI 
Review at: https://yearn-docs-git-fork-marcoworms-ui-fork-guide.yearn.farm/developers/v2/fork-yearn-ui

add UI forking guide using macarena

---

docs/developers/v2/DEPLOYMENT.md
docs/getting-started/products/token-addresses.md

Also updates the deployment file to add links to scans
Review at:
https://yearn-docs-git-marcoworms-patch-1.yearn.farm/getting-started/products/token-addresses

Update token addresses page to include contracts

---

docs/resources/links.md

fix risk dashboard link

---

docs/contributing/contributor-tools.md

Fixing a few typos

---

docs/getting-started/using-yearn.md

make arrows match the color of others on this page, add index numbers to improve readability of each image section
*link linter is failing but flagged link is working as expected

improve getting started example color

---

docusaurus.config.js

Add the git link to the meta property to be able to fetch it from remote

feat: Add meta git property

---

docs/partners/introduction.md

since fees are dynamic the partner docs now show how to lookup fees for a vault

improve partner docs

---

docs/getting-started/intro.md

update introduction copy

---

docs/developers/v2/DEPLOYMENT.md

both broken links are private repos explicitly marked on the text as private so no need to change this I think
[✖] https://github.com/yearn/chief-multisig-officer
[✖] https://github.com/yearn/yearn-strategies/issues

improve v2 deployment copy

---

docs/getting-started/products/yCRV.md
docs/getting-started/products/ycrv/faq.md
docs/getting-started/products/ycrv/guide.md
docs/getting-started/products/ycrv/overview.md
sidebars/sidebarsGettingStarted.js

add ycrv docs

---

docs/developers/v2/CONTRACTS_REVIEW.md
docs/developers/v2/EMERGENCY.md
docs/developers/v2/additional-resources.md
docs/getting-started/guides/how-to-understand-yvault-roi.md
docs/getting-started/intro.md
docs/getting-started/products/yvaults/overview.md
docs/getting-started/products/yvaults/vaults-and-strategies.md
docs/getting-started/products/yvaults/yvault-advantages.md
docs/security/index.md

edit copy around docs to make it more concise, fix dead links
2 links flagged by linter are up and probably have some sort of protection and the bot doesn't reach them but they both work when clicked

Improve copy

---

docs/resources/r-and-d/vecrv-boosts.md
sidebars/sidebarsGettingStarted.js

move it to the research section as a deprecated page

deprecate old yvecrv page

---

docs/developers/v2/DEPLOYMENT.md

since #39 seems to be almost done but inactive I copied the commit from it, fixed merge conflicts, and applied a requested review
deadlinks seem to be all private repos (I can't access to known haha)

hijack PR #39 and apply review requests

---

docs/getting-started/products/ycrv/overview.md
docs/getting-started/products/yvaults/overview.md
versioned_docs/version-0.4.2/yearn-lens/yearn-lens.md
versioned_docs/version-0.4.3/yearn-lens/yearn-lens.md

- Remove reference to Zapper Zaps contracts (we've disabled the zaps and we will come up with a better solution in the future)
- Linting

Remove reference to Zapper's zaps contract since those have been disabled + linting

---

docs/getting-started/guides/how-to-understand-strategies-descriptions.md

Adding proper grammar to line 102.

Correcting text grammatically

---

docs/partners/introduction.md

copy changes and grammatical edits to the partners intro page

partner-docs-copy-edits.md

---

docs/contributing/contribute.md

improve contribute.md grammar

---

docs/getting-started/products/yvaults/overview.md

update vault fee structure

---

docs/developers/v2/entities.md
docs/developers/v2/queries.md
docs/developers/v2/subgraph-info.md
docs/developers/v2/yearn-data.md
sidebars/sidebarsDevelopers.js

resstructure data docs to add exporter

---

docs/developers/v2/hacking-with-yearn.md

this info has placeholder stuff and typos, it also implies there is a function for flashloan on the vault
found this out while testing yGenius, wanted to fix here in the source!
closes #307

remove misleading info

---

docs/partners/yvtokens-as-collateral.md

linter says link is down but is up :)

add more info on airdrop protection when using yvtokens as collateral

---

docs/partners/submit_pr.md

- add start_date
- add info for partner logo prs

add more info about partner logos

---

docs/getting-started/products/yvaults/overview.md
docs/getting-started/using-yearn.md

closes #323 
There is a page that needs a more detailed review because we changed the way we display APY in the new dashboard and I don't want to just delete the old info: https://docs.yearn.finance/getting-started/guides/how-apy-works

update dashboard images

---

docs/getting-started/products/yvaults/v3.md

- update wording 
- delete hackmd link

fix: small updates to v3

---

docs/partners/partner-tracker.md

Add Base partner tracker address

---

docs/contributing/governance/veyfi.md

also updates style of this list

update dyfi redemption address

---

docs/getting-started/products/ycrv/guide.md

Removed FTX. 
No need to reference it

Removed FTX reference. Update guide.md

---

docs/getting-started/products/yeth/overview.md

todo: where to check vote half-time variable?

add info about yeth vote weight

---

docs/partners/yvtokens-as-collateral.md

update collateral page for more recent changes, add V3 and disclaimer for new know issue

fix: collateral page

---

docs/getting-started/products/veyfi.md

Add yG-yvWETH-1, yG-yvUSDC-1, yG-yvDAI-1 to the docs per [this Snapshot](https://snapshot.org/#/veyfi.eth/proposal/0x9feea11e65b5d62093a4ce1d387acd946030df532f7e89e06c72a27fe594c6b9).

Update veYFI Docs with Yearn v3 Vault Gauges 

---

docs/developers/v2/entities.md
docs/developers/v2/yswaps.md

chore: fix typos

---

docs/getting-started/products/veyfi.md

- Add gauge registry and controller addresses
- Cleanup, remove duplicate texts

Update veYFI docs

---

docs/developers/v3/overview.md

update protocol address provider address

fix: address provider

---

docs/getting-started/products/ylockers/overview.md
docs/getting-started/products/ylockers/yprisma/overview.md
docs/getting-started/products/ylockers/yprisma/yprisma-faq.md

added the new deployed contract addresses to the docs that were missing.

update deployed contract addresses

---

docs/getting-started/products/veyfi.md

* added sdYFI v2 vault and upYFI vault gauges to list.
* added index numbers to gauges
* added line about how to query gauges on the registry.

chore: update veYFI gauges

---

package.json
yarn.lock

updates Docusaurus and its dependencies from 3.2.1 to 3.4.0

chore: update docusaurus version

---

docs/getting-started/products/addresses.md

change etherscan.com to be the correct etherscan.io

fix: broken etherscan links

---

docs/unused/guides/how-to-understand-yveCRV.md

There is probably a better way to check the workflow, but I don't know it. so lets push this to see if I fixed it.

chore: check workflow

---

.github/workflows/documentation.yml
docs/unused/guides/how-to-understand-yveCRV.md

Had the wrong secrets and the wrong API call. Should work now

chore: fix algolia workflow

---

.gitignore
.gitmodules

Clean up and update submodules

Fix: submodules

---

src/css/custom.css
src/pages/index.module.css

- Search bar styling updated to be consistent for both mobile and desktop
- Updated landing page banners to be centered on mobile and make titles more legible.

fix: css tweaks for mobile search and landing screen

---

docs/developers/v1/interfaces.md

Fixed:
Replaced func with function for clarity and consistency.
Why it's useful:
This change enhances readability and ensures proper terminology usage in the documentation or code.

Improved terminology for clarity

---

docs/developers/addresses/veyfi-contracts.md

Updates the veYFI gauge list to reflect most recent additions
- yGauge Curve COVEYFI Factory yVault
- yGauge DAI-2 yVault
- yGauge WETH-2 yVault
- yGauge crvUSD-2 yVault
- yGauge yGOLD-styETH
- yGauge USDS-1 yVault

Chore: add new veyfi gauges

---

.github/workflows/documentation.yml
scripts/fetchedAddressData.json

Clean up old build actions that used github pages

Chore: clean up actions

---

scripts/fetchedAddressData.json

update address check data object from checks run on my branch.
I need to troubleshoot to determine why this isn't working on the yearn/master repo

chore: update address checks data

---

docs/developers/security/multisig.md

chore: update multisig signers

---

docs/developers/smart-contracts/V2/BaseStrategy.md
docs/developers/smart-contracts/deprecated/V2/version-0.4.2/smart-contracts/BaseStrategy.md
docs/developers/smart-contracts/deprecated/V2/version-0.4.3/smart-contracts/BaseStrategy.md

This pull request contains changes to improve clarity, correctness and structure.

fix: typos in documentation files

---

docs/getting-started/products/yvaults/yvaults-faq.md

Update yVault FAQ to include base as an option

Chore:  yVault FAQ update-add base to gimme

---

sidebars/sidebarsDeveloperDocs.js
sidebars/sidebarsUserDocs.js

add link to brand assets page for user docs sidebar and developer docs front-end sidebar

feat: add brand assets link

---

docs/contributing/governance/veYFI-comp-summary.md
docs/contributing/governance/veYFI-intro.md
docs/developers/smart-contracts/deprecated/V2/version-0.4.2/process-and-procedures/naming-convention.md
docs/developers/v2/naming-convention.md
docs/developers/v2/vault-factory.md
docs/getting-started/guides/how-apy-works.md
docs/getting-started/guides/how-boost-works.md
docs/getting-started/guides/how-to-understand-strategies-descriptions.md
docs/getting-started/products/ylockers/overview.md
docs/getting-started/products/ylockers/ycrv/overview.md
docs/getting-started/products/ylockers/ycrv/ycrv-faq.md
docs/getting-started/products/ylockers/ycrv/ycrv-guide.md
docs/resources/deprecated/vecrv-boosts.md
docs/resources/deprecated/yPrisma/yprisma-faq.md
docs/resources/deprecated/yPrisma/yprisma-guide.md
docs/resources/faq.md
docs/unused/guides/how-to-understand-yveCRV.md

update curve URLs due to hack of their DNS.

chore: update curve URLs

---

docs/getting-started/products/yvaults/yBold.md
scripts/fetchedAddressData.json
sidebars/sidebarsUserDocs.js

Adds documentation about Yearn's new yBOLD product

feat: add yBOLD

---

docs/developers/security/multisig.md

- add Ephy to Multi-sig page
- remove monoloco from multi-sig page
- update lumberg key and attestation

Chore: update msig signers

---

docs/contributing/governance/veYFI-comp-summary.md
docs/contributing/governance/veYFI-intro.md

should be boosties.cove.finance

replace broken cove links
