yearn/yearn-devdocs

docs/v1/introduction.md
Fixes broken info hint box syntax on: 
https://yearn.github.io/yearn-devdocs/v1/introduction/
=> Fix info hint syntax on v1 intro page.

docs/v2/smart-contracts/BaseStrategy.md, docs/v2/smart-contracts/BaseWrapper.md, docs/v2/smart-contracts/registry.md, docs/v2/smart-contracts/vault.md, templates/contract.ejs, versioned_docs/version-0.3.0/smart-contracts/BaseStrategy.md, versioned_docs/version-0.3.1/smart-contracts/BaseStrategy.md, versioned_docs/version-0.3.1/smart-contracts/registry.md, versioned_docs/version-0.3.1/smart-contracts/vault.md, versioned_docs/version-0.3.2/smart-contracts/BaseStrategy.md, versioned_docs/version-0.3.2/smart-contracts/registry.md, versioned_docs/version-0.3.2/smart-contracts/vault.md, versioned_docs/version-0.3.3/smart-contracts/BaseStrategy.md, versioned_docs/version-0.3.3/smart-contracts/registry.md, versioned_docs/version-0.3.3/smart-contracts/vault.md, versioned_docs/version-0.3.4/smart-contracts/BaseStrategy.md, versioned_docs/version-0.3.4/smart-contracts/registry.md, versioned_docs/version-0.3.4/smart-contracts/vault.md, versioned_docs/version-0.3.5/smart-contracts/BaseStrategy.md, versioned_docs/version-0.3.5/smart-contracts/registry.md, versioned_docs/version-0.3.5/smart-contracts/vault.md, versioned_docs/version-0.4.2/smart-contracts/BaseStrategy.md, versioned_docs/version-0.4.2/smart-contracts/BaseWrapper.md, versioned_docs/version-0.4.2/smart-contracts/registry.md, versioned_docs/version-0.4.2/smart-contracts/vault.md
Removes `@notice` from the generated docs and also removes it from the template `contract.ejs` 
Issue: https://github.com/yearn/yearn-devdocs/issues/11
=> docs: remove notice tag

src/pages/index.module.css
Finish the fix for #33 
Visited links were not showing. Below is a screenshot of how visited links look now.
=> fix: make visited links visible and with the same color as not visited

docs/developers/v2/DEPLOYMENT.md, docs/developers/v2/ledger-plugin.md, sidebars/sidebarsDevelopers.js
With the upcoming Ledger Plugin, a few extra step should be added when a vault is endorsed.  
This PR adds a new step in `Scaling up / Moving to Endorse` and add a new page `docs/developers/v2/ledger-plugin.md` to provider a small overview of the process to add the new Vault to the Ledger Plugin.  
The process to install and test the plugin is available on the ledger's documentation and not retranscribed here.
=> feat: add small documentation for ledger plugin

docs/developers/v2/EMERGENCY.md, versioned_docs/version-0.4.3/smart-contracts/test/TestGuestList.md
removes the deprecated "GuestList" link from the latest version of the docs
close #127 
also removes private links from and close #125
=> refactor: remove deprecated and private links

docs/partners/introduction.md
The new text should better clarify how yearn charges fees and shares profits with partners, also adds an example profit-sharing case
=> refactor: rewrite partnership-program docs

docs/developers/v2/getting-started.md
if anyone has a backup we could change for it, but I haven't found a history for the vesper doc that was blanked
=> remove broken strategy example

docs/developers/v2/DEPLOYMENT.md
adds the following to the deployment page:
- Governance MS: 0xC0E2830724C946a6748dDFE09753613cd38f6767
- Treasury: 0x89716ad7edc3be3b35695789c475f3e7a3deb12a
- Strategist MS: 0x72a34AbafAB09b15E7191822A679f28E067C4a16
- Registry: 0x727fe1759430df13655ddb0731dE0D0FDE929b04
- Health Check: 0xf13Cd6887C62B5beC145e30c38c4938c5E627fe0
- Governance Multisig: 0xb6bc033D34733329971B938fEf32faD7e98E56aD
- Strategist Multisig: 0x6346282DB8323A54E840c6C772B4399C9c655C0d
- Treasury: 0x1DEb47dCC9a35AD454Bf7f0fCDb03c09792C08c1
- registry: 0x3199437193625DCcD6F9C9e98BDf93582200Eb1f
- Health Check: 0x32059ccE723b4DD15dD5cb2a5187f814e6c470bC
----
=> add fantom and arbitrum deployment addresses

docusaurus.config.js
telegram preview link was showing the old logo
preview:
=> fix og image

sidebars/sidebarsGettingStarted.js
this is a suggestion, but since we dont use this product anymore I think we should remove it to not lead users to reading docs on outdated products
=> deprecate yvecrv from sidebar

docs/resources/links.md
we didn't have it linked anywhere before, I did not add in versioned docs because they are autogenerated
=> add link to Lens repo

docs/getting-started/products/yvaults/vaults-and-strategies.md
The purpose of this PR is to correct the blog link: `What are Vaults and Strategies? `. Added to `Vault and Strategies Introduction` subsection as shown in the screenshot below. Currently the link isn't redirecting to the blog that the user is expected to consult.
The motivation for applying this change is to improve the user experience, fix the current issue and make all links work as planned.
=> fix: Change docs link of the 'Vault and Strategies' section

docs/contributing/governance/veyfi.md
=> add dyfi addresses

docs/getting-started/products/ycrv/overview.md, docs/getting-started/products/yprisma/farming.md, docs/getting-started/products/yprisma/overview.md, sidebars/sidebarsGettingStarted.js
=> add yprisma docs

.gitignore, docs/resources/links.md, docs/resources/risks/risk-score.md
- Added link to seafood in `links.md` under "vault detail reference" section
- Added line near the top with link to seafood to view risk scores.
- Added link to https://seafood.yearn.watch/risk in TVL impact section of `risk.md` in addition to the existing yearnwatch link.
- Some automatic formatting changes (like the other issues I just submitted)
Question:
Is there a linting config file in the repo that I can use to disable certain linter items? In the meantime I added my own and updated the .gitignore so it doesn't get added.
=> Add seafood #373

docusaurus.config.js
Update docusaurus.config.js to replace the old brownie based mix links to the modern foundry and apeworx templates.
update katex dependency to latest one ref. in docusarus official docs.
fix js-doc typechecking
=> chore(docusaurus): update footer links and config

docs/getting-started/products/ylockers/overview.md, docs/getting-started/products/ylockers/ycrv/overview.md, docs/getting-started/products/ylockers/ycrv/ycrv-faq.md, docs/getting-started/products/ylockers/yprisma/yprisma-faq.md
smol change: add link to veCRV documentation in yCRV and yLocker docs as we never really explain how ve-tokenomics work.
=> add veCRV info links

src/css/custom.css
updates to page width and sidebar styling to reflect changes from #445.
=> feat: update page width and sidebar styling

docs/resources/risks/index.md
The PR adds a page to the risks section that gives an overview of risks for the layman.
This is laying the groundwork for more prominently displaying the risks section for users and added context seems helpful.
=> Feat: add risks overview page

.gitignore, docusaurus.config.js, package.json, src/theme/Layout/index.js
This PR adds an element to the top right corner of the screen showing what branch is being served when running dev builds. It runs when using `yarn start`. This is intended as a useful tool when actively working in multiple branches to keep track of what is what.
There should be no change to the production version of the site.
=> Feat: add branch display to dev builds

docs/contributing/documentation/working-on-docs.md
"are store" corrected to "are store**d**".
=> Typo Update working-on-docs.md

docs/resources/deprecated/ygift.md, docs/resources/deprecated/ytrade.md, docs/resources/faq.md
Changed "ETH or ENS address" to "ETH or ENS addresses" for plural agreement.
Updated "previous chosen token" to "previously chosen token" for correct adverb usage.
Corrected "significant implication" to "significant implications" for plural form.
Fixed "overtime" to "over time" for correct phrasing.
Adjusted "bring this up with the team of Discord" to "bring this up with the team on Discord" for correct preposition use.
=> Grammar and Clarity Improvements

docs/contributing/governance/veyfi.md, docs/developers/v2/ledger-plugin.md, docs/developers/v2/yswaps.md
This pull request contains changes to improve clarity, correctness and structure.
**Description correction:**
Corrected "lock earn" to "lock to earn".
Corrected "toeknOut" to "tokenOut".
Corrected "straighforward" to "straightforward".
Corrected "step by step" to "step-by-step".
Please review the changes and let me know if any additional changes are needed.
=> fix: typos in documentation files

docs/resources/deprecated/ygift.md
The error "contributor's" instead of "contributors'" involves the incorrect use of the apostrophe to indicate possession. In this context, "contributors" (plural) should be used with an apostrophe after the "s" to show ownership, i.e., "contributors' gift" (gift from multiple contributors). This is important because the incorrect apostrophe usage can affect the readability and professionalism of the text, creating an impression of carelessness.
=> Fix Possessive Apostrophe in "Contributor's" to "Contributors'"

.github/workflows/addressChecks.yml, scripts/fetchedAddressData.json
Action was failing to push to the master branch due to branch protections. The fix removes the push step and instead includes the output in the issue so it can be updated manually.
=> Fix: AddressCheck action

src/components/veYFI-calculator.tsx
- Fix to remove the veYFI lock calculator modal when calculating boost from USD or vault shares. 
- Improved the button so it isn't disabled when the veYFI lock calculator is being used.
=> fix: remove lock calculator when not needed and improve button behavior

docs/developers/data-services/yearn-data.md
yDaemon docs are ded. Need to bring them back but for now will just kill the link.
=> fix: remove dead ydaemon docs link

.gitignore, package.json, scripts/fetchedAddressData.json
The contract address checks are being run nightly but the json that the on-page validation components read from are not. I have added a step to the `yarn start` and `yarn build` commands that runs the script to check contract addresses. This will assure that anytime a new commit is pushed to the repo from someone building the site, it will have the most updated contracts and will reflect that on the timestamp.
=> fix: update dev build flow to check addresses

README.md, package.json
I added a command to run the `addressCheck` script in the yarn build command in #532. This causes problems when building in github workflows if I don't pass the alchemy api key to the workflow step. I considered a few options to fix:
1. Add alchemy API key to the needed step.
2. Create additional build option that doesn't have script call and use that in workflows.
3. Remove script call in build step
Looking at the workflows, I am already running the script later most of the time. I added the script call to the `yarn start` command in order to make sure that any PR I made would include an updated check on the contracts to try to keep checks up to date. I don't use the build command often so option 1 seems unnecessary and adds complexity. likewise for option 2. So I will remove the script …
=> fix: remove address check from build command

docs/developers/v3/vault_management.md
Add warning to prevent someone deploying the RoleManager from adding the same address as `governance` and `management`
=> chore: add warning to roleManager deployment instructions
